# Generated by Django 2.2.3 on 2019-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190713_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='attending',
            field=models.CharField(choices=[('', 'You are attending ....'), ('all', 'All'), ('reception', 'Reception'), ('party', 'Dinner & Party')], max_length=255),
        ),
    ]
