# Generated by Django 2.2.3 on 2019-07-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190713_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
